### ISSUE TITLE
Checked / Unchecked events not wired

### ISSUE THREAD

**Issue by drabb** [jqueryfiletree/jqueryfiletree#20]
The docs mention events for checked / unchecked (filetreechecked / filetreeunchecked) - but these don't seem to actually be wired up.

You can accomplish similar behavior binding your owns events on the custom connector's input elements.  

At very least please update docs to reflect.

**Comment by daverogers** [comment]
Yeah, I'm not sure what happened on that one. I probably thought the same thing as you, that users can do the same thing on their own pretty simply, but forgot to remove that from the readme. I may end up doing something like that in the future if/when I need to use them in JQFT, but for now I just opted to take them out of the docs.
