### ISSUE TITLE
does not work on MSWindows

### ISSUE THREAD

**Issue by korenanzo** [jqueryfiletree/jqueryfiletree#21]
If in the "dir" parameter is contained a MSWIndows style volume, for example "D:/" the jQUeryFileTree.js does not work;
the problem is probably at line 138 where  
`
$(this).attr('rel').match(relPattern)[0])
`
using relPattern that don't consider the possibility of having "c:" ath the beginning of the rel.

Actually I don't undertand the purpose of this match: removing the match() :
`
 _this.showTree($(this).parent(), $(this).attr('rel'));
`
the program seems to work good..

RIc

**Comment by daverogers** [comment]
Yeah, that was a remnant of the original project. Perhaps it was a way to clean up any attempt to tamper, but the connector scripts should be filtering and validating anything sent from client-side anyways so I'll be removing this in the next release.
