### ISSUE TITLE
How to add folder on the fly?

### ISSUE THREAD

**Issue by RuslanLomov** [jqueryfiletree/jqueryfiletree#25]
I have a function that adds new folder to the workspace.
How to add that folder to your file tree?
$('.tree')
.fileTree({
root : root,
script : 'ViewController',
}, function(file) {
})
i tried to create 
<h>var folderToAppend =  "li class="directory collapsed">a href="#" rel="" +userRoot + name + "/\">"+ name + "/a/li"</h> (with angle scopes)
and append it to ul in working file tree.
It works, but new folder not clickable nor selectable and shows itself like not a part of file tree.
I can see new folder added after i collapse and expand folder where new folder was created.
How to make adding new folder work on the fly?

**Comment by daverogers** [comment]
So you're creating that folder to the server via another script/process, and are trying to append to the filetree without refreshing but it's not clickable, right? Or are you expecting JQFT to create that folder in the backend?

**Comment by RuslanLomov** [comment]
Hello,thnks for your reply!
I created button that creates new folder im memory  and adds some data about that folder to the database. Now i want to append that new folder to file tree. I can see my new folder after reopen file tree directory in which it was created, then it appears. I tried to append the same html structure as in your file tree for the folder to existing html page but it doesn't recognize itself as directory(not clickable,selectable). How do I udate your magic tree without reopening folder or F5?
Thanks for you time.

**Comment by RuslanLomov** [comment]
it would be cool to have some kind of refresh trigger method that will for example not only add new folder but also will rename folder and all dependent folders inside renamed one(change each 'rel' parameter)

**Comment by daverogers** [comment]
Yeah, the .on click handler ([L119](https://github.com/jqueryfiletree/jqueryfiletree/blob/master/src/coffeescript/jQueryFileTree.coffee#L119)) doesn't have anything specified for the selector ("ul.jqueryFileTree" might work), so it's not expecting or looking for a dynamically-added element. You can try that and if it works, shoot me a pull request.

As for the refresh trigger method idea, I'm not sure how many people would use that. I actually did in one of my projects and I think I just fired a .trigger() event for the parent directory to close, then had a callback to trigger it again to reopen. Should be pretty easy to implement outside of the plugin for anybody who needs to do that :) Once the .on handler accepts dynamically-appended directories, this is pretty much what you could do to open it by default, if you wanted to.

**Comment by RuslanLomov** [comment]
>

**Comment by RuslanLomov** [comment]
> Yeah, the .on click handler (L119) doesn't have anything specified for the selector ("ul.jqueryFileTree" might work), so it's not expecting or looking for a dynamically-added element. 
Sorry,what do you mean?
 `$el.find('LI A').on options.folderEvent, () ->` is on click directory function but I need to append `<li class="directory collapsed"><a href="#" rel="src/main/ss/">ss</a></li>` that i manually created outside of file tree script.<br>
As I Inderstand your tree shows files and waiting on `$el.find('LI A').on options.folderEvent, () ->` function until any directory was pressed.<br>
How do I interrupt that process and add html  `var folderToAppend="<li class="directory collapsed"><a href="#" rel="src/main/ss/">ss</a></li>"` to the working set of files already presented in file tree?<br>
I tried to call` $.appendNewFolder(folderToAppend);` outside of your script and 
`$.appendNewFolder = function(data) {handleResult(data);}`  inside your script <br>
Everything works fine and new appended folder become clickable but the bug comes up after i try to close and open parent folder(the new folder always stays on the bottom of parent one). So I find this method unefficient<br>
P.S. sorry for interrupting your code:)

**Comment by RuslanLomov** [comment]
please,email me ruslanlomov@hotmail.com

**Comment by daverogers** [comment]
When the parent folder is opened, it is setting an event listener for each element under it explicitly, so you can expand those directories. But when you manually add a folder to that parent, it has no event listener attached to it (unless you close/reopen the folder, which will refresh the event listeners).

Try out the latest version I just committed (2.0.3) and see if that works for you. The [Github.io site](http://jqueryfiletree.github.io/) has been updated and when I duplicate a folder from Chrome's dev tools, it opens; I expect your dynamically-added folders to work from now on too so long as the folder structure and data attributes are the same.

**Comment by RuslanLomov** [comment]
after you change `$el.find('LI A').on(options.folderEvent, function() {` to  r`eturn $el.on(options.folderEvent, 'li a', function() {` bug appears after you close and open parent directory, directory inside has problem with expanding(not setting expand class)

**Comment by daverogers** [comment]
Oh funky. I'll have to look into that.

**Comment by RuslanLomov** [comment]
Hello)) how is it going?

**Comment by daverogers** [comment]
Yeah, I don't have a whole lot of time for OS projects. I reverted this change in the latest release. I'll have to tinker with it in a dev branch (as I should have in the first place). I'm thinking this will require a bigger change, assigning one event handler for the whole filetree, not attaching one for each folder.

**Comment by daverogers** [comment]
Check out the 'delegate-events' branch: https://github.com/jqueryfiletree/jqueryfiletree/tree/delegate-events

This not only gets rid of the shit-ton of events binding to each folder (which could really slow down very large file trees), it should also accomplish your goal of being able to open dynamically-added directories.

**Comment by RuslanLomov** [comment]
did yoy test it on your http://jqueryfiletree.github.io/? I see same bug with openning parent folder second time

**Comment by daverogers** [comment]
I did. I am not seeing what you're seeing.

**Comment by RuslanLomov** [comment]
Ok,the bug dissapeared but still main question remains: "How  dynamically append new folder?"<br>
I tried to append new folder to the `#basic-file-tree` on  http://jqueryfiletree.github.io/  with browser console command like this:<br>
`$("#basic-file-tree").find("li.directory.expanded").find("ul.jqueryFileTree").append("<li class=\"directory collapsed\"><a href=\"#\" rel=\"/src/\">a</a></li>")`.<br>
Appended folder is visible but doesn't behave like folder(not clickable)

**Comment by daverogers** [comment]
Ah, that's right, I updated the master branch to 2.0.4, so the demo site is set to that.

I created a folder for you to test this:
http://jqueryfiletree.github.io/branches/delegate-events/

**Comment by RuslanLomov** [comment]
Ok,the bug dissapeared but still main question remains: "How  dynamically append new folder?"<br>
I tried to append new folder to the `#basic-file-tree` on  http://jqueryfiletree.github.io/  with browser console command like this:<br>
`$("#basic-file-tree").find("li.directory.expanded").find("ul.jqueryFileTree").append("<li class=\"directory collapsed\"><a href=\"#\" rel=\"/src/\">a</a></li>")`.<br>
Appended folder is visible but doesn't behave like folder(not clickable)

**Comment by RuslanLomov** [comment]
Great, I think it started to work! Great decision with delegate method! Never knew about that.<br> 
I will try to test a bit more later in the evening and will tell you the final result. Thanks for your time!

**Comment by daverogers** [comment]
Yeah, I had never actually used it before, but always wanted to try it out for this project especially. Turned out to be easier to use than I thought it would be. But yeah, whenever you have time to play with it that'd be great :)

**Comment by RuslanLomov** [comment]
hello!
i tested new file tree. Everything works fine with delegate function.
Btw new code looks much more elegant now
Issue closed i think

**Comment by daverogers** [comment]
Awesome!
