### ISSUE TITLE
How to know the last selected folder?

### ISSUE THREAD

**Issue by unix4you2** [jqueryfiletree/jqueryfiletree#26]
Hi!

I'm writting an extension for this tool that gives to the user the possibility to create a new folder or file, change permissions and more.  A simplified file manager that could be attached to any jqueryfiletree but I need to know hot to get the last folder or file selected in the jqueryfiletree and if there is any possibility to select files using double click.

Thanks!

**Comment by unix4you2** [comment]
Hello again.

I decided to add an event to the connector over the anchor created in the tree for files and folders using a global javascript variable to save the data:

* For folders:
` OnClick=\"LastFolderSelected='" . htmlentities($_POST['dir'] . $file) . "';\" `

* For files:
`OnClick=\"LasFileSelected='" . htmlentities($_POST['dir'] . $file) . "';\"`

Then I can use that vars in any JS to know the last path or file selected in the tree..  Should be this feature usefful?  Could I add it to a new PR over all connectors?

Regards.

**Comment by daverogers** [comment]
I haven't worked with this project in a pretty long while so I'm a bit rusty with details on the fly, but that could be done with a trigger outside of JQFT. Something like:

```js
$('.filetree').on('filetreeclicked', function(e, data) {
 console.log( data.type );
 // assign to LastFileSelected / LastFolderSelected, and/or take other action(s) you want
});
```

It just depends what you're doing/what you need, I suppose.

**Comment by unix4you2** [comment]
Nice @daverogers  I'll change my code for that.

I changed the connectors too, to receive a GET param to specify if you want to see files and folders or folders only because when you are going to use this plugin to select where do you want to save or create something people would like to select only from folders.

If you think this features is ussefull I could open a new PR.

Regards.
