### ISSUE TITLE
Fix $.slideDown() options - replace 'speed' with 'duration'

### ISSUE THREAD

**Issue by servocoder** [jqueryfiletree/jqueryfiletree#31]
I have found a bug in `$.slideDown()` jquery method options at:
https://github.com/jqueryfiletree/jqueryfiletree/blob/master/src/jQueryFileTree.js#L140
Option `speed` should be replaced with `duration`, because `expandSpeed` doesn't affect on sliding speed.

Check http://api.jquery.com/slidedown/

**Comment by daverogers** [comment]
Good catch. That's what I get for making a quick change before committing at 2 am and assuming I don't need to check the docs just to make sure ;)

**Comment by daverogers** [comment]
Addressed in commit e14165d
