### ISSUE TITLE
refresh part/full tree

### ISSUE THREAD

**Issue by vsraptor** [jqueryfiletree/jqueryfiletree#33]
How do you guys force refresh of part of the tree programatically ?
For example let say I'm simulating directory tree, when I delete a file or directory I need to force the JFT to refresh portion of the tree..

**Comment by c-robinson** [comment]
I'd be interested in this too, though my reason is that I might want to reload the filetree with a different root directory, from a user-selectable list.

**Comment by daverogers** [comment]
See 39
