### ISSUE TITLE
Methods - Is there any method available to refresh the tree fully or partially

### ISSUE THREAD

**Issue by ntha314159** [jqueryfiletree/jqueryfiletree#39]
Is there any method to refresh the tree fully or partially.

If not please suggest a way to go about achieving it.

Many Thanks in Advance.

**Comment by daverogers** [comment]
You could have jQuery click the folder you want to refresh, then click it again on callback. There is currently no method to call directly, but that's essentially the same functionality that would be used anyway.

**Comment by ntha314159** [comment]
Thanks ! it worked

**Comment by wings27** [comment]
Clicking twice on the folder using jQuery is likely to fail when _expandSpeed_ or _collapseSpeed_ is set. 
That is because the second click happens during when the folder is expanding (or collapsing).
So in my humble opinion, it is still essential to have a refresh method, not to mention the click-twice-method is just a workaround in the first place.

**Comment by easylogic** [comment]
```javascript

function refresh_node (dir) { 
    var $a = $el.find("a[rel='"+dir+"']");
    $a.parent().addClass('collapsed');
    $a.trigger('click');
}

refresh_node('/sample/');
```

**Comment by easylogic** [comment]
```javascript
function refresh_all() {
    var tree = $el.data('fileTree');
    $el.empty();
    tree.showTree($el, escape(tree.options.root), function () {
        console.log('file tree reload');
    });
}

refresh_all() ;    // refresh  root node 
```

**Comment by eneiluj** [comment]
Thanks @easylogic , refresh_all() works fine.

Maybe a documented and more direct method like
``` javascript
$('div#mytree').data('fileTree').refresh();
```
would be usefull.

**Comment by atifone** [comment]
change line 202 from : 
`if (!data) {`

to : 

`if (!data || (Object.prototype.toString.call(args) === '[object Object]' && args.reload)) {` 
Now,  to reload the 'fileTree' pass "reload: true" in the arguments array.

solution by : [https://stackoverflow.com/users/894876/ixm](url)
