### ISSUE TITLE
Get full path from file

### ISSUE THREAD

**Issue by malvess** [jqueryfiletree/jqueryfiletree#42]
Hello,

I'd like to know how to get the full path on click event. 

Someone can help me?

Thanks

**Comment by daverogers** [comment]
It's in the rel attribute, ie `rel="/webfiles/dist/images/"` - is that what you want? If you want something else, you'd have to build it in, that is you'll pass an attribute (like `data-path="C:/this/is/the/path.jpg"`) along via your connector and grab that via jQuery.

**Comment by malvess** [comment]
Ok, that is it. Tks a lot!
