### ISSUE TITLE
problem with the php file

### ISSUE THREAD

**Issue by Andro-Boy** [jqueryfiletree/jqueryfiletree#43]
Hi,
I am trying to make it work perfectly but i couldn't ...
The page loads successfully but the tree doesn't show instead it's the .php script, all written on the left side instead of the actual tree.

i reviewed and compared the online test page, it the same code but i don't know what is the problem.

Any suggestions ?

**i am using firefox , chrome has the cross-origin problem.

**Comment by daverogers** [comment]
What changes did you make to the PHP file?
