### ISSUE TITLE
Error with Bower command

### ISSUE THREAD

**Issue by stonio** [jqueryfiletree/jqueryfiletree#45]
Bower (version 1.7.9) command `bower install jqueryfiletree --save` does not work. I have the following error:

<pre>
ECMDERR Failed to execute "git clone https://github.com/jqueryfiletree/jqueryfiletree.git -b 2.1.3 --progress . --depth 1", exit code of #128 Cloning into '.'... remote: Counting objeremote: Compressing objects: 100% (74/74), done.         remote: Total 82 (delta 1), reused 54 (delta 0), pack-reused 0         Checking connectivity... done. Note: checking out '7432f0899b67471016d933fa258300b44936abe2'.  You are in 'detached HEAD' state. You can look around, make experimental changes and commit them, and you can discard any commits you make in this state without impacting any branches by performing another checkout.  If you want to create a new branch to retain commits you create, you may do so (now or later) by using -b with the checkout command again. Example:    git checkout -b <new-branch-name>  fatal: cannot create directory at 'dist/connectors/PHP-Laravel-5.*': Invalid argument warning: Clone succeeded, but checkout failed. You can inspect what was checked out with 'git status' and retry the checkout with 'git checkout -f HEAD'

Additional error details:
Cloning into '.'...
remote: Counting objects: 82, done.
remote: Compressing objects: 100% (74/74), done.
remote: Total 82 (delta 1), reused 54 (delta 0), pack-reused 0
Checking connectivity... done.
Note: checking out '7432f0899b67471016d933fa258300b44936abe2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

fatal: cannot create directory at 'dist/connectors/PHP-Laravel-5.*': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
</pre>

**Comment by daverogers** [comment]
Ah, yeah, was wondering if that asterisk was going to cause issues at some point. Restructured it in the 2.1.4 release. Let me know if that fixes it for you.

**Comment by stonio** [comment]
Version 2.1.4 has fixed this issue on Windows
