### ISSUE TITLE
Add an option to specify allowed file extensions

### ISSUE THREAD

**Issue by onet4** [jqueryfiletree/jqueryfiletree#58]
What about adding an option to specify allowed file extensions to be listed?

```js
$('.filetree-folders-only').fileTree(
    {
        script: 'connectors/jqueryFileTree.php',
        fileExtensions: 'js,txt,html',
    }
);
```

**Comment by daverogers** [comment]
I think it'd be best to just do that in your connector script. That's where you'll actually be filtering by extension anyways.

**Comment by onet4** [comment]
I know it can be done with a connector script. But handling it only with a connector script is really hard when file extensions need to be specified dynamically.

**Comment by daverogers** [comment]
Ah, so it sounds like you're setting up a search/filter. It may be worthwhile to do, in that case; maybe as a connectorOptions array so you can specify what you need for your connector and take it from there.

**Comment by daverogers** [comment]
Added issue #60 to address this.
