### ISSUE TITLE
filetreeinitiated event not being triggered

### ISSUE THREAD

**Issue by grovert100** [jqueryfiletree/jqueryfiletree#63]
I haven't had time to test, but I think line 142-143 should be changed from:

```
                if options.root == dir
                    $el.find('UL:hidden').show( callback? )
```

To:
```
                if options.root == dir
                    $el.find('UL:hidden').show({complete: finishCallback})
```

If options.root is '/' (default value), then the comparison above will be true and 'finishCallback' never gets called.

**Comment by daverogers** [comment]
merging your code. thanks :)
