### ISSUE TITLE
JQuery File Tree doesn't work with JQuery ui draggable

### ISSUE THREAD

**Issue by alexisgstalter** [jqueryfiletree/jqueryfiletree#68]
Hello,
I'm trying to make directories draggable with Jquery UI to make a customized permission folder hierarchy by dropping it to add the permission. But it doesn't work, my Jquery UI installation work (all li elements which aren't in the tree view can move).

my server part code for the generation: 

![image](https://user-images.githubusercontent.com/17162196/29862830-f73bde14-8d6d-11e7-819a-359028550eaf.png)

my Jquery : 

![image](https://user-images.githubusercontent.com/17162196/29862856-0f3a0b44-8d6e-11e7-902f-5d58c574182e.png)

thanks for attention

**Comment by daverogers** [comment]
that's a pretty cool idea, but just outside the scope of what this lib does. i'm going to close the ticket because it's not a jqueryfiletree issue, but i do want to see if you make any progress on that in future updates :)
